### ISSUE TITLE
Install Ansible on Linux build VM

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#17]
2018-03-08T16:37:16.0211330Z ##[debug]sudoEnabled=false
2018-03-08T16:37:16.0234375Z ##[debug]args=null
2018-03-08T16:37:16.0255510Z ##[debug]failOnStdErr=true
2018-03-08T16:37:16.0276344Z ##[debug]task result: Failed
2018-03-08T16:37:16.0366525Z ##[error]Could not locate Ansible. Either it is not installed or its path is not present on ENVIRONMENT PATH variable
2018-03-08T16:37:16.0403603Z ##[debug]Processed: ##vso[task.issue type=error;]Could not locate Ansible. Either it is not installed or its path is not present on ENVIRONMENT PATH variable
2018-03-08T16:37:16.0451045Z ##[debug]Processed: ##vso[task.complete result=Failed;]Could not locate Ansible. Either it is not installed or its path is not present on ENVIRONMENT PATH variable
2018-03-08T16:37:16.0521073Z ##[section]Finishing: Run playbook

**Comment by rifaterdemsahin** [comment]
Could not locate Ansible. Either it is not installed or its path is not present on ENVIRONMENT PATH variable

**Comment by rifaterdemsahin** [comment]
ssh keys need to registered as well
![image](https://user-images.githubusercontent.com/5270036/37170923-291c2c50-2304-11e8-8e61-c0ed0622ac8c.png)

**Comment by rifaterdemsahin** [comment]
https://eschrader.com/2017/05/17/using-visual-studio-team-services-build-tasks-for-linux-over-ssh/

**Comment by rifaterdemsahin** [comment]
command lining up
![image](https://user-images.githubusercontent.com/5270036/37171048-828a3426-2304-11e8-9422-d80fe8d3dc01.png)

**Comment by rifaterdemsahin** [comment]
rpm did not work ...we need to understand the operating system of the agent.

trying apt-get

![image](https://user-images.githubusercontent.com/5270036/37171168-e0a35ae2-2304-11e8-91d4-61695f8a9aea.png)

**Comment by rifaterdemsahin** [comment]
did not see the linux variables
so adding a step to see them all

![image](https://user-images.githubusercontent.com/5270036/37171314-5ea8b1c6-2305-11e8-850b-ef5642c4d184.png)

**Comment by rifaterdemsahin** [comment]
When the image is not ready it takes time for the image to be created as well.
![image](https://user-images.githubusercontent.com/5270036/37171366-8a545fd2-2305-11e8-9068-33477737b36d.png)

**Comment by rifaterdemsahin** [comment]
timing is also important
![image](https://user-images.githubusercontent.com/5270036/37171402-ae834026-2305-11e8-8ee5-097fa0c82c09.png)

**Comment by rifaterdemsahin** [comment]
Asked this question
https://devops.stackexchange.com/questions/3583/installing-ansible-controller-to-build-agents

**Comment by rifaterdemsahin** [comment]
I might need to run my controller as a dedicated machine
![image](https://user-images.githubusercontent.com/5270036/37171672-89146e5e-2306-11e8-80dc-1498bde37c2d.png)

**Comment by rifaterdemsahin** [comment]
Linux deployment
![image](https://user-images.githubusercontent.com/5270036/37171740-c3dcd99a-2306-11e8-8c7d-5e7dd7f69288.png)

**Comment by rifaterdemsahin** [comment]
We learned that it is using Ubuntu
![image](https://user-images.githubusercontent.com/5270036/37171770-dbbe72ee-2306-11e8-9094-58077106fa2e.png)

**Comment by rifaterdemsahin** [comment]
Lol it is in docker
https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/16.04/standard/Dockerfile

Ansible is not here
![image](https://user-images.githubusercontent.com/5270036/37171853-1d98df10-2307-11e8-9304-ae32eaf69090.png)

**Comment by rifaterdemsahin** [comment]
Maybe installing this over docker would make more sense?
https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/16.04/standard/Dockerfile

Important things are already installed in here
![image](https://user-images.githubusercontent.com/5270036/37171947-5f9ae0b6-2307-11e8-9ef4-be13c7c00da9.png)

**Comment by rifaterdemsahin** [comment]
What could I do ?

Use parallels
- Start ubuntu
- Install docker
- Install msdocker file
- Add ansible into the mix
- Add the desktop ubuntu do the build agent. ( Do registration )
- Create a container
- Deploy the container to the kubernetes ?

**Comment by rifaterdemsahin** [comment]
Cancelling after 27 minutes

![image](https://user-images.githubusercontent.com/5270036/37172464-bf98485e-2308-11e8-87a7-c20c0641df6a.png)

**Comment by rifaterdemsahin** [comment]
Getting a new image for this one
![image](https://user-images.githubusercontent.com/5270036/37172512-e582faa0-2308-11e8-8e70-3bd6d13e33d0.png)

**Comment by rifaterdemsahin** [comment]
should have the base Linux image...every time download does not make sense.
![image](https://user-images.githubusercontent.com/5270036/37172633-4c28d3b0-2309-11e8-919c-20380d49de4e.png)

**Comment by rifaterdemsahin** [comment]
All tasks are not written in a way that hosted Linux can see
![image](https://user-images.githubusercontent.com/5270036/37172778-af51a962-2309-11e8-8a2d-b19248d669b5.png)

**Comment by rifaterdemsahin** [comment]
testing line by line

sudo apt-get update
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get install ansible

**Comment by rifaterdemsahin** [comment]
this one worked...16 seconds apt-get update
![image](https://user-images.githubusercontent.com/5270036/37172862-f77155f8-2309-11e8-8043-24c316e234ad.png)

**Comment by rifaterdemsahin** [comment]
thinking this is going to fail big time....MS also should not let that happen
![image](https://user-images.githubusercontent.com/5270036/37172910-1db91fe8-230a-11e8-9773-46e83131b54e.png)

Nope I am wrong
![image](https://user-images.githubusercontent.com/5270036/37173191-d3c7bc22-230a-11e8-9802-a601ad38e066.png)

**Comment by rifaterdemsahin** [comment]
starting from the kubernetes is maybe the way to go...this way of triggering from the vm might not be the best way to go
![image](https://user-images.githubusercontent.com/5270036/37173330-326005aa-230b-11e8-9d1f-c4919f854d5d.png)

**Comment by rifaterdemsahin** [comment]
ansible repo addin took 3 seconds

2018-03-08T19:57:51.0838240Z 0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
2018-03-08T19:57:52.4954250Z  Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications— automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.
2018-03-08T19:57:52.4967059Z 
2018-03-08T19:57:52.4982321Z http://ansible.com/
2018-03-08T19:57:52.4995018Z  More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
2018-03-08T19:57:52.9576523Z gpg: keyring `/tmp/tmpvxdzpg43/secring.gpg' created
2018-03-08T19:57:52.9612241Z gpg: keyring `/tmp/tmpvxdzpg43/pubring.gpg' created
2018-03-08T19:57:52.9686273Z gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
2018-03-08T19:57:53.2902590Z gpg: /tmp/tmpvxdzpg43/trustdb.gpg: trustdb created
2018-03-08T19:57:53.2916663Z gpg: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
2018-03-08T19:57:53.2930228Z gpg: Total number processed: 1
2018-03-08T19:57:53.2944276Z gpg:               imported: 1  (RSA: 1)

**Comment by rifaterdemsahin** [comment]
hmmmm not stuck ?
![image](https://user-images.githubusercontent.com/5270036/37173481-9e8b43fc-230b-11e8-9933-868a0c0fcf36.png)

2018-03-08T20:01:29.0301434Z Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
2018-03-08T20:01:29.0314509Z Get:2 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease [18.0 kB]
2018-03-08T20:01:29.0481619Z Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
2018-03-08T20:01:29.1156002Z Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
2018-03-08T20:01:29.1534221Z Hit:5 https://packages.microsoft.com/repos/azure-cli wheezy InRelease
2018-03-08T20:01:29.1823956Z Hit:6 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease
2018-03-08T20:01:29.2084647Z Hit:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
2018-03-08T20:01:29.2107934Z Hit:8 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
2018-03-08T20:01:29.3022154Z Hit:9 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease
2018-03-08T20:01:29.4893946Z Hit:10 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial InRelease
2018-03-08T20:01:29.6769187Z Get:11 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [470 B]
2018-03-08T20:01:29.7076396Z Hit:12 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
2018-03-08T20:01:29.8765780Z Fetched 18.5 kB in 1s (17.8 kB/s)
2018-03-08T20:01:31.1372769Z Reading package lists...
2018-03-08T20:01:31.1767939Z ##[debug]rc:0
2018-03-08T20:01:31.1792347Z ##[debug]success:true
2018-03-08T20:01:31.2789664Z ##[section]Finishing: Latest Release Via Apt-Get Ansible Install

**Comment by rifaterdemsahin** [comment]
disabled the last step not to have a misunderstanding

![image](https://user-images.githubusercontent.com/5270036/37173570-df690062-230b-11e8-8583-aadb756678b9.png)

**Comment by rifaterdemsahin** [comment]
hosted agents and time limits
![image](https://user-images.githubusercontent.com/5270036/37173698-2bb8dd66-230c-11e8-9d1a-2075d0c5c1c7.png)

**Comment by rifaterdemsahin** [comment]
started Docker pull on my mac
![image](https://user-images.githubusercontent.com/5270036/37173727-455a2afe-230c-11e8-8f62-08d98e23e2be.png)

**Comment by rifaterdemsahin** [comment]
Creted this one
![image](https://user-images.githubusercontent.com/5270036/37173806-87bde700-230c-11e8-8a19-165e76c21ed1.png)

Total time this might be **faster**
![image](https://user-images.githubusercontent.com/5270036/37173819-9429b53c-230c-11e8-830f-b8ce03b188de.png)

**Comment by rifaterdemsahin** [comment]
it looks like hosted one getting stuck in this state

Get:12 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [470 B]
Hit:13 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
Fetched 18.5 kB in 1s (16.0 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  python-cffi-backend python-crypto python-cryptography python-ecdsa
  python-enum34 python-httplib2 python-idna python-ipaddress python-jinja2
  python-markupsafe python-paramiko python-pkg-resources python-pyasn1
  python-setuptools python-six python-yaml sshpass
Suggested packages:
  python-crypto-dbg python-crypto-doc python-cryptography-doc
  python-cryptography-vectors python-enum34-doc python-jinja2-doc doc-base
  python-setuptools-doc
The following NEW packages will be installed:
  ansible python-cffi-backend python-crypto python-cryptography python-ecdsa
  python-enum34 python-httplib2 python-idna python-ipaddress python-jinja2
  python-markupsafe python-paramiko python-pkg-resources python-pyasn1
  python-setuptools python-six python-yaml sshpass
0 upgraded, 18 newly installed, 0 to remove and 0 not upgraded.
Need to get 4030 kB of archives.
After this operation, 29.6 MB of additional disk space will be used. 

**there could be a yes no question ?**

**Comment by rifaterdemsahin** [comment]
Still can not understand from the log.... it does not work thats all

2018-03-08T20:08:07.8840695Z   python-enum34 python-httplib2 python-idna python-ipaddress python-jinja2
2018-03-08T20:08:07.8857915Z   python-markupsafe python-paramiko python-pkg-resources python-pyasn1
2018-03-08T20:08:07.8875175Z   python-setuptools python-six python-yaml sshpass
2018-03-08T20:08:07.9596595Z 0 upgraded, 18 newly installed, 0 to remove and 0 not upgraded.
2018-03-08T20:08:07.9613276Z Need to get 4030 kB of archives.
2018-03-08T20:08:07.9629836Z After this operation, 29.6 MB of additional disk space will be used.
2018-03-08T20:13:13.6680857Z ##[debug]Re-evaluate condition on job cancellation for step: 'Latest Release Via Apt-Get Ansible Install'.
2018-03-08T20:13:13.6977051Z Do you want to continue? [Y/n] 
2018-03-08T20:13:13.8079035Z ##[error]The operation was canceled.
2018-03-08T20:13:13.8188118Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-03-08T20:13:13.8232107Z ##[section]Finishing: Latest Release Via Apt-Get Ansible Install

**Comment by rifaterdemsahin** [comment]
in Docker the image is for ansible is here
![image](https://user-images.githubusercontent.com/5270036/37174112-858ac0ba-230d-11e8-8612-eda1cac1ffcf.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37174169-b2395cf2-230d-11e8-9614-65ac0b5b8f9a.png)


Kitematic create from your images
![image](https://user-images.githubusercontent.com/5270036/37174188-bf9d6064-230d-11e8-8443-2224ac13eb75.png)

**Comment by rifaterdemsahin** [comment]
running where
![image](https://user-images.githubusercontent.com/5270036/37174231-d7e41aa0-230d-11e8-85df-25d25d695b5e.png)

Shell integration is great
![image](https://user-images.githubusercontent.com/5270036/37174264-e9a419de-230d-11e8-8acd-b32751e6e771.png)

**Comment by rifaterdemsahin** [comment]
2.0 is running inside my docker
![image](https://user-images.githubusercontent.com/5270036/37174326-13997dce-230e-11e8-8320-207873a5a7c7.png)

in my pc 

Erdems-MacBook-Pro:~ rifaterdemsahin$ ansible --version
ansible **2.4.3.0**
  config file = None
  configured module search path = [u'/Users/rifaterdemsahin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
Erdems-MacBook-Pro:~ rifaterdemsahin$

**Comment by rifaterdemsahin** [comment]
it tries
![image](https://user-images.githubusercontent.com/5270036/37174444-65e6e454-230e-11e8-9f6e-20aae2cb02bc.png)

**Comment by rifaterdemsahin** [comment]
normal operating system
![image](https://user-images.githubusercontent.com/5270036/37174489-8db3cb8c-230e-11e8-8f64-3302c77c3212.png)

**Comment by rifaterdemsahin** [comment]
not much programs there
![image](https://user-images.githubusercontent.com/5270036/37174543-b9f2d896-230e-11e8-8df0-89f0266c6a3d.png)


could not do ssh but we have the logic here
![image](https://user-images.githubusercontent.com/5270036/37174871-bc1b7a0a-230f-11e8-991f-57c8ac7269f3.png)

**Comment by rifaterdemsahin** [comment]
in the background it gives too open error
![image](https://user-images.githubusercontent.com/5270036/37174928-dc23cd98-230f-11e8-88ed-4e7d77728cd3.png)

ansible all -i 35.205.237.237, -m ping --private-key ~/ssh/id_rsa -vvvv


Permissions 0755 for '/root/ssh/id_rsa' are too open.

**Comment by rifaterdemsahin** [comment]
keys only need to be readable by you 
![image](https://user-images.githubusercontent.com/5270036/37175002-18062522-2310-11e8-9cf6-3eb2a8c182c5.png)

**Comment by rifaterdemsahin** [comment]
after 400 setting is here
![image](https://user-images.githubusercontent.com/5270036/37175044-34250868-2310-11e8-96ae-1c9aa8b4763a.png)

after 400 now copy paster error from google drive
![image](https://user-images.githubusercontent.com/5270036/37175074-5365e7c4-2310-11e8-870d-985f06833111.png)

**Comment by rifaterdemsahin** [comment]
missing begin marker

![image](https://user-images.githubusercontent.com/5270036/37175192-b1fbf7ce-2310-11e8-8ece-4bdd6395836c.png)

**Comment by rifaterdemsahin** [comment]
Change ansible versions...the key in the public may be the problem... but,  mac connects it...the key in the docker can be an issue.

Practical file transfer is a need this thing kills lots of time.

**Comment by rifaterdemsahin** [comment]
So many images here

![image](https://user-images.githubusercontent.com/5270036/37175720-4768df06-2312-11e8-81f4-3c1d7248a267.png)

**Comment by rifaterdemsahin** [comment]
start from your ubuntu and build on it ?
![image](https://user-images.githubusercontent.com/5270036/37175872-ba78ca92-2312-11e8-9dd0-9426765a0aea.png)

**Comment by rifaterdemsahin** [comment]
414 M is the 16.4 
stable one
![image](https://user-images.githubusercontent.com/5270036/37175937-da7eebaa-2312-11e8-8073-b60ce6bb7d07.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37175955-e74c3ebe-2312-11e8-9aaa-63f31f4537c3.png)


it jumps to 60 maybe the other ubuntu shares some parts?

**Comment by rifaterdemsahin** [comment]
_xec gets into my mac terminal as whell
![image](https://user-images.githubusercontent.com/5270036/37176020-12281d92-2313-11e8-847d-8fcae1d6f13d.png)

**Comment by rifaterdemsahin** [comment]
even ping module is not there
![image](https://user-images.githubusercontent.com/5270036/37176065-2a158020-2313-11e8-9351-925df2354db0.png)


and it would lose state so how can i install something than capture?

**Comment by rifaterdemsahin** [comment]
restart and check
![image](https://user-images.githubusercontent.com/5270036/37176105-42978792-2313-11e8-82ea-0cc5b68a6dac.png)

no after restart it is there
![image](https://user-images.githubusercontent.com/5270036/37176144-64ca55ba-2313-11e8-8cc7-3aed1add1d19.png)


reboot mac and check

**Comment by rifaterdemsahin** [comment]
docker kitematic lost all my images?
![image](https://user-images.githubusercontent.com/5270036/37177548-b5ab53cc-2317-11e8-918c-4549619f4faa.png)

**Comment by rifaterdemsahin** [comment]
maybe too beta
![image](https://user-images.githubusercontent.com/5270036/37177582-d0eecb3c-2317-11e8-850f-9fed72f0d3c6.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37177601-dd5e8308-2317-11e8-8251-ab36b619cf1d.png)

**Comment by rifaterdemsahin** [comment]
here is the statefull container
![image](https://user-images.githubusercontent.com/5270036/37178180-9f6f1510-2319-11e8-9734-8b454f6b3745.png)

**Comment by rifaterdemsahin** [comment]
after hard core start stop it is gone....

hmmm state is tried to preserve but not there
![image](https://user-images.githubusercontent.com/5270036/37178256-e35b089c-2319-11e8-8682-72c8f2654065.png)

**Comment by rifaterdemsahin** [comment]
this is so skinny there is not much there
![image](https://user-images.githubusercontent.com/5270036/37178312-f9cfab14-2319-11e8-8f8f-c68017af2290.png)

**Comment by rifaterdemsahin** [comment]
get ubuntu and get ansible 
create your own image 
than go to kubernetes
![image](https://user-images.githubusercontent.com/5270036/37178377-35939732-231a-11e8-8859-183f2b716db1.png)

**Comment by rifaterdemsahin** [comment]
Get them in the same room
![image](https://user-images.githubusercontent.com/5270036/37178448-6e8da7d0-231a-11e8-8f72-b28470fd6665.png)
![image](https://user-images.githubusercontent.com/5270036/37178459-7a0184e2-231a-11e8-8236-19c811a8cd51.png)


https://docs.docker.com/engine/reference/commandline/commit/#examples

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37178550-bb95e72c-231a-11e8-9f06-2bf76c5771fa.png)

now there is 2 ubuntu
![image](https://user-images.githubusercontent.com/5270036/37178603-da982086-231a-11e8-8c9b-ea46332f4a79.png)

**Comment by rifaterdemsahin** [comment]
if this thing gets deployed easy to the kubernetes...all infra will live in one place.one hardware

What is the wodn side to that argument ?

**Comment by rifaterdemsahin** [comment]
this is an ubuntu now we wanna work for
![image](https://user-images.githubusercontent.com/5270036/37200495-d6c9db7c-237c-11e8-9195-a173ae57cd5d.png)

**Comment by rifaterdemsahin** [comment]
Created a docker image of Ansible 
![image](https://user-images.githubusercontent.com/5270036/37204633-823b2496-2389-11e8-9d4c-1a080078a13a.png)

**Comment by rifaterdemsahin** [comment]
Decide is if this is usable
