### ISSUE TITLE
Create Servers Via Ansible

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#2]
- Services
- Databases

**Comment by rifaterdemsahin** [comment]
Our YML File for Ansible
http://docs.ansible.com/ansible/latest/guide_gce.html

name: Create instance(s)
hosts: localhost
connection: local
gather_facts: no

vars:
service_account_email: aif-318@developer.gserviceaccount.com
credentials_file: /project.json
project_id: project-id
machine_type: n1-standard-1
image: debian-7

tasks:

name: Launch instances
gce:
instance_names: dev
machine_type: "{{ machine_type }}"
image: "{{ image }}"
service_account_email: "{{ service_account_email }}"
credentials_file: "{{ credentials_file }}"
project_id: "{{ project_id }}

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37121818-38bbb7ba-2256-11e8-9337-6f04dba94488.png)

https://console.cloud.google.com/compute/instances?project=adaptiveintelligenceframework

**Comment by rifaterdemsahin** [comment]
added to here
![image](https://user-images.githubusercontent.com/5270036/37121944-a6040066-2256-11e8-80a3-55bc31708126.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37122001-d13b054a-2256-11e8-8739-be130c57d8ca.png)


Created keys folder to place the google Json
![image](https://user-images.githubusercontent.com/5270036/37122060-f91b804e-2256-11e8-956b-8293995731a1.png)

**Comment by rifaterdemsahin** [comment]
/Users/rifaterdemsahin/keys/adaptiveintelligenceframework-f0833ece51c8.json

**Comment by rifaterdemsahin** [comment]
Note that when using the inventory script **gce.py**, you also need to populate the **gce.ini** file that you can find in the contrib/inventory directory of the ansible checkout.

![image](https://user-images.githubusercontent.com/5270036/37122321-fdfd113a-2257-11e8-8197-2178fbdcf6e1.png)


![image](https://user-images.githubusercontent.com/5270036/37122584-fa399ebe-2258-11e8-81d6-3d70c80a215e.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37122705-75b3468a-2259-11e8-966a-3654769b01ab.png)

**Comment by rifaterdemsahin** [comment]
under git repo on mac double ansible
![image](https://user-images.githubusercontent.com/5270036/37122908-35bd45c0-225a-11e8-985c-5058e93902fd.png)

**Comment by rifaterdemsahin** [comment]
we have the google library now
![image](https://user-images.githubusercontent.com/5270036/37122942-548bd1e2-225a-11e8-9a44-444c26a18ceb.png)

**Comment by rifaterdemsahin** [comment]
starters
![image](https://user-images.githubusercontent.com/5270036/37122974-6e659012-225a-11e8-90ac-837d56535d1a.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37123000-883b1160-225a-11e8-9b41-fa9d7f9e5da1.png)

**Comment by rifaterdemsahin** [comment]
no change after path setting
![image](https://user-images.githubusercontent.com/5270036/37123054-bdfce1c0-225a-11e8-90f8-d617d355e0d6.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37123226-49586974-225b-11e8-9390-6c89a51c14c9.png)

**Comment by rifaterdemsahin** [comment]
https://libcloud.apache.org/blog/2015/02/18/libcloud-0-17-0-released.html

Sudo force
![image](https://user-images.githubusercontent.com/5270036/37123271-79adbea8-225b-11e8-8e48-cabf05004d3b.png)

**Comment by rifaterdemsahin** [comment]
Started to get meaning full errors

Erdems-MacBook-Pro:inventory rifaterdemsahin$ ./gce.py --list
Traceback (most recent call last):
  File "./gce.py", line 508, in <module>
    GceInventory()
  File "./gce.py", line 170, in __init__
    self.driver = self.get_gce_driver()
  File "./gce.py", line 318, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py", line 878, in __init__
    raise ValueError('Project name must be specified using '
ValueError: Project name must be specified using "project" keyword.
Erdems-MacBook-Pro:inventory rifaterdemsahin$

**Comment by rifaterdemsahin** [comment]
**export PYTHONPATH=/Library/Python/2.7/site-packages/**

Erdems-MacBook-Pro:lib rifaterdemsahin$ ansible --version
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/rifaterdemsahin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

**Comment by rifaterdemsahin** [comment]
now under site-packages and path reset
![image](https://user-images.githubusercontent.com/5270036/37123890-cc2be914-225d-11e8-8bd1-47f7714fbf55.png)

**Comment by rifaterdemsahin** [comment]
error changed to datacenter
![image](https://user-images.githubusercontent.com/5270036/37123933-0c43893a-225e-11e8-8933-705332e1b013.png)

**Comment by rifaterdemsahin** [comment]
after empty datacenter
![image](https://user-images.githubusercontent.com/5270036/37124052-99d07268-225e-11e8-9aa4-71278f25ce39.png)


Traceback (most recent call last):
  File "./gce.py", line 508, in <module>
    GceInventory()
  File "./gce.py", line 170, in __init__
    self.driver = self.get_gce_driver()
  File "./gce.py", line 318, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py", line 887, in __init__
    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/base.py", line 651, in __init__
    api_version=api_version, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/common/base.py", line 1013, in __init__
    self.connection = self.connectionCls(*args, **conn_kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py", line 75, in __init__
    **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 619, in __init__
    user_id, key, self.scopes, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 463, in __init__
    raise GoogleAuthError('PyCrypto library required for '
libcloud.common.google.GoogleAuthError: **'PyCrypto library required for Service Account Authentication.'**
Erdems-MacBook-Pro:inventory rifaterdemsahin$

**Comment by rifaterdemsahin** [comment]
Erdems-MacBook-Pro:inventory rifaterdemsahin$ sudo pip install pycrypto
Password:
The directory '/Users/rifaterdemsahin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/rifaterdemsahin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 1.1MB/s 
Installing collected packages: pycrypto
  Running setup.py install for pycrypto ... done
Successfully installed pycrypto-2.6.1
Erdems-MacBook-Pro:inventory rifaterdemsahin$

**Comment by rifaterdemsahin** [comment]
Erdems-MacBook-Pro:inventory rifaterdemsahin$ ./gce.py --list
Traceback (most recent call last):
  File "./gce.py", line 508, in <module>
    GceInventory()
  File "./gce.py", line 170, in __init__
    self.driver = self.get_gce_driver()
  File "./gce.py", line 318, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py", line 887, in __init__
    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/base.py", line 651, in __init__
    api_version=api_version, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/common/base.py", line 1013, in __init__
    self.connection = self.connectionCls(*args, **conn_kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py", line 75, in __init__
    **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 627, in __init__
    self.token_info = self.auth_conn.get_new_token()
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 516, in get_new_token
    return self._token_request(request)
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 352, in _token_request
    raise GoogleAuthError('Invalid authorization response, please '
libcloud.common.google.GoogleAuthError: '**Invalid authorization response, please check your credentials.'**

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37124200-2aa90638-225f-11e8-8e43-6229dc3685c9.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/37124209-38df02e8-225f-11e8-90f7-786110002763.png)

**Comment by rifaterdemsahin** [comment]
Last login: Wed Mar  7 18:39:27 on ttys001
Erdems-MBP:~ rifaterdemsahin$ cd /Library/Python/2.7/site-packages/
Erdems-MBP:site-packages rifaterdemsahin$ sudo nano secrets.py 
Password:
Erdems-MBP:site-packages rifaterdemsahin$ more secrets.py
GCE_PARAMS = ('aif-318@project.googleusercontent.com', '/Users/rifaterdemsahin/keys/adaptiveintelligenceframework-f0833ece51c8.json')
GCE_KEYWORD_PARAMS = {'project': 'adaptiveintelligenceframework', 'datacenter': ''}


maybe datacenter ?

setting defaults here
![image](https://user-images.githubusercontent.com/5270036/37124268-76a8bc5e-225f-11e8-9f6d-6c5f2713ccdb.png)


europe-west1

updated version secrets.py

GCE_PARAMS = ('aif-318@project.googleusercontent.com', '/Users/rifaterdemsahin/keys/adaptiveintelligenceframework-f0833ece51c8.json')
GCE_KEYWORD_PARAMS = {'project': 'adaptiveintelligenceframework', 'datacenter': 'europe-west1'}

**Comment by rifaterdemsahin** [comment]
export GCE_CREDENTIALS_FILE_PATH=/Users/rifaterdemsahin/keys/adaptiveintelligenceframework-f0833ece51c8.json

set et

**Comment by rifaterdemsahin** [comment]
Erdems-MacBook-Pro:inventory rifaterdemsahin$ export GCE_CREDENTIALS_FILE_PATH=/Users/rifaterdemsahin/keys/adaptiveintelligenceframework-f0833ece51c8.json
Erdems-MacBook-Pro:inventory rifaterdemsahin$ 
Erdems-MacBook-Pro:inventory rifaterdemsahin$ ./gce.py --list
Traceback (most recent call last):
  File "./gce.py", line 508, in <module>
    GceInventory()
  File "./gce.py", line 170, in __init__
    self.driver = self.get_gce_driver()
  File "./gce.py", line 318, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py", line 887, in __init__
    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/base.py", line 651, in __init__
    api_version=api_version, **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/common/base.py", line 1013, in __init__
    self.connection = self.connectionCls(*args, **conn_kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py", line 75, in __init__
    **kwargs)
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 627, in __init__
    self.token_info = self.auth_conn.get_new_token()
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 516, in get_new_token
    return self._token_request(request)
  File "/Library/Python/2.7/site-packages/libcloud/common/google.py", line 352, in _token_request
    raise GoogleAuthError('Invalid authorization response, please '
libcloud.common.google.GoogleAuthError: 'Invalid authorization response, please check your credentials.'
Erdems-MacBook-Pro:inventory rifaterdemsahin$
